# Generated by Django 4.2.13 on 2024-05-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='brojPitanja',
            field=models.IntegerField(),
        ),
    ]
