# Generated by Django 4.2.13 on 2024-05-16 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_alter_quiz_brojpitanja"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="pitanje1",
            new_name="pitanje",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="brojPitanja",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="user",
        ),
        migrations.AddField(
            model_name="quiz",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
