# Generated by Django 4.2.13 on 2024-05-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_pitanje1_question_pitanje_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="creator",
        ),
        migrations.AddField(
            model_name="quiz",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
