# Generated by Django 4.2.13 on 2024-05-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_quiz_creator_quiz_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="updated",
        ),
    ]
