# Generated by Django 4.2.13 on 2024-05-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_quiz_created_quiz_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="user",
        ),
    ]
