# Generated by Django 4.2.13 on 2024-05-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_question_odgovorkorisnika'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='brojPitanja',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
