# Generated by Django 4.2.13 on 2024-05-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_quiz_brojpitanja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='brojPitanja',
            field=models.IntegerField(null=True),
        ),
    ]
