# Generated by Django 4.2.13 on 2024-05-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_answer_player_quiz_usercreator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='userCreator',
            new_name='author',
        ),
    ]
