# Generated by Django 4.2.13 on 2024-05-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_timer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistic",
            name="time",
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name="Timer",
        ),
    ]
