# Generated by Django 4.2.13 on 2024-05-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_remove_statistic_time_quizstatistic"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizstatistic",
            name="quizName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
