# Generated by Django 4.2.13 on 2024-05-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_remove_quizstatistic_quizname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quizstatistic",
            options={"ordering": ["-datePlayed"]},
        ),
    ]
