# Generated by Django 4.2.13 on 2024-05-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_alter_quizstatistic_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quizstatistic",
            options={},
        ),
    ]
