# Generated by Django 4.2.13 on 2024-05-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_alter_quizstatistic_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizstatistic",
            name="datePlayed",
            field=models.DateField(default="21:19 21.05.2024"),
        ),
    ]
