# Generated by Django 4.2.13 on 2024-05-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_quizstatistic_dateplayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizstatistic',
            name='datePlayed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
