# Generated by Django 4.2.13 on 2024-05-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_quizstatistic_dateplayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
