# Generated by Django 4.2.13 on 2024-05-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_quiz_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created']},
        ),
    ]
