# Generated by Django 4.2.13 on 2024-05-23 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_alter_quiz_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timeer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time1", models.DateTimeField(default=django.utils.timezone.now)),
                ("time2", models.DateTimeField(default=django.utils.timezone.now)),
                ("finalTime", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
