# Generated by Django 4.2.13 on 2024-06-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_timeer"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Timeer",
            new_name="Timer",
        ),
    ]
